### ISSUE TITLE
Judge multiple testcases in a single submission

### ISSUE THREAD

**Issue by ncthuc** [judge0/judge0#223]
A very typical use case when judging a coding solution is testing the code against a **set of testcases** (pairs of input/expected_output). 

This is very similar to the `submissions/batch` but in this new use case, `language_id`  and `source_code` stay the same, an array of testcases is provided. The workers have only to do one time of source code preparation/compilation, and run the result script/binary multiple times against each of the testcases provided, which can save some server resources.

In this scenario, an extra api param can also be provided to control if the judging process should stop immediately on first wrong/failed testcase to save server resources.

Do you think this is a good feature to have?

**Comment by hermanzdosilovic** [comment]
Hi @ncthuc,

currently, there is no plan to support this feature since it does not scale well with the current design of what submission is and how it is processed.

I can get into more details about this if you want.

The best thing that currently works very well, as you mentioned, are batched submissions.

BR,
Herman
