### ISSUE TITLE
[Question] How we use webhook in Judge0 ?

### ISSUE THREAD

**Issue by anubhabmondalDirac** [judge0/judge0#276]
Hi Sir, I deploy judge0 using docker. Now I want to use webhook. I can't find any documentation or code example. I want to use webhook or callback URL when code compilation is done and generate a token. Is there any possible way we can do that?
Can you please provide any help? Some code example or documentation would be great.
Thanks in advance. @hermanzdosilovic @mejibyte @cesar

**Comment by hermanzdosilovic** [comment]
Does search for "callback_url" on Judge0 documentation website at https://ce.judge0.com/ help?

**Comment by hermanzdosilovic** [comment]
I don't have any code examples, but the idea is that when you create a submission you give Judge0 a URL which it will call with PUT once the submission is done. Inside this PUT request, Judge0 will give you the same data that you would otherwise get with `GET /submissions/<token>?base64_encoded=true` request.

**Comment by anubhabmondalDirac** [comment]
@hermanzdosilovic Thank you so much for your reply.
